Repository IntersectMBO/cardano-ledger, pull requests merged in 2019-03, with the labels that each got.

#314 using := for let binding symbol
  latex/delegation.tex
  latex/epoch.tex
  latex/ledger.tex
  latex/notation.tex
  latex/utxo.tex
Labels: formal-spec, shelley

#303 Rename `LowerThanThdAndNotAlreadyConfirmed`
  specs/ledger/hs/src/Ledger/Update.hs
Labels: byron-shelley bridge, executable-model

#349 Use `lib.nix` instead of `nix/fetch-nixpkgs.nix`.
  .gitignore
  README.md
  dependencies/non-integer/doc/default.nix
  docs/delegation_design_spec/default.nix
  latex/default.nix
  nix/fetch-nixpkgs.nix
  nix/nixpkgs-src.json
  specs/chain/latex/default.nix
  specs/ledger/latex/default.nix
  specs/semantics/latex/default.nix
Labels: devops

#348 Specify that `upropTTL` is.
  specs/ledger/latex/update-mechanism.tex
Labels: byron-shelley bridge, formal-spec
